<?php

namespace App\Providers;

use App\Models\Attendance;
use App\Models\Employee;
use App\Models\Shift;
use App\Database\Schema\Grammars\LegacyMySqlGrammar;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Collection;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->configureLegacyMysqlSchema();
        Schema::defaultStringLength(191);
        $publicUploadRoot = config('filesystems.disks.public.root');

        File::ensureDirectoryExists($publicUploadRoot);
        File::ensureDirectoryExists($publicUploadRoot . DIRECTORY_SEPARATOR . 'company-images');
        File::ensureDirectoryExists($publicUploadRoot . DIRECTORY_SEPARATOR . 'company-documents');

        if (!app()->runningInConsole()) {
            try {
                if (
                    Schema::hasTable('employees')
                    && Schema::hasTable('leave_requests')
                    && Schema::hasTable('leave_types')
                    && Schema::hasTable('attendance')
                ) {
                    $today = now('Asia/Manila');
                    $this->syncEmployeeLeaveStatuses($today);
                    $this->syncAutoGeneratedAttendanceRows($today);
                }
            } catch (\Throwable $e) {
                // Silently ignore to avoid breaking early migrations/installs
            }
        }
    }

    private function syncEmployeeLeaveStatuses(Carbon $today): void
    {
        $todayString = $today->toDateString();

        Employee::where('status', 3)
            ->whereNotExists(function ($query) use ($todayString) {
                $query->select(DB::raw(1))
                    ->from('leave_requests')
                    ->whereColumn('leave_requests.employee_id', 'employees.id')
                    ->where('leave_requests.status', 2)
                    ->where('leave_requests.start_date', '<=', $todayString)
                    ->where('leave_requests.end_date', '>=', $todayString);
            })
            ->update(['status' => 1]);

        Employee::whereIn('status', [1, 2])
            ->whereExists(function ($query) use ($todayString) {
                $query->select(DB::raw(1))
                    ->from('leave_requests')
                    ->whereColumn('leave_requests.employee_id', 'employees.id')
                    ->where('leave_requests.status', 2)
                    ->where('leave_requests.start_date', '<=', $todayString)
                    ->where('leave_requests.end_date', '>=', $todayString);
            })
            ->update(['status' => 3]);
    }

    private function syncAutoGeneratedAttendanceRows(Carbon $today): void
    {
        $employees = Employee::query()
            ->whereHas('user')
            ->with([
                'user:id,employee_id',
                'shiftAssignments.shift',
            ])
            ->get(['id']);

        if ($employees->isEmpty()) {
            return;
        }

        $rangeEnd = $today->copy()->endOfDay();
        $rangeStart = $today->copy()->subDays(6)->startOfDay();
        $employeeIds = $employees->pluck('id')->all();
        $leaveLookups = $this->buildLeaveLookups($employeeIds, $rangeStart, $rangeEnd);
        $attendanceLookup = Attendance::query()
            ->whereIn('emp_id', $employeeIds)
            ->where('punch_type', 'in')
            ->whereBetween('attendance_date', [$rangeStart->toDateString(), $rangeEnd->toDateString()])
            ->get()
            ->keyBy(function (Attendance $attendance) {
                return $attendance->emp_id . '|' . $attendance->attendance_date->toDateString();
            });

        for ($offset = 0; $offset < 7; $offset++) {
            $checkDate = $today->copy()->subDays($offset);
            $dateString = $checkDate->toDateString();
            $dayOfWeek = $checkDate->format('D');

            foreach ($employees as $employee) {
                $user = $employee->user;
                if (!$user) {
                    continue;
                }

                $dayShift = $this->resolveActiveShiftFromLoadedAssignments($employee, $checkDate);
                $existingRecord = $attendanceLookup->get($employee->id . '|' . $dateString);

                if (!$dayShift || !is_array($dayShift->days_of_week) || !in_array($dayOfWeek, $dayShift->days_of_week, true)) {
                    if ($this->isAutoGeneratedAttendanceRecord($existingRecord)) {
                        $existingRecord->delete();
                    }

                    continue;
                }

                $shiftStart = Carbon::parse($dateString . ' ' . $dayShift->start_time, 'Asia/Manila');
                $hasApprovedLeave = isset($leaveLookups['approved'][$employee->id][$dateString]);
                $hasApprovedPaidLeave = isset($leaveLookups['paid'][$employee->id][$dateString]);

                if ($today->gt($shiftStart)) {
                    $expectedStatus = $hasApprovedLeave ? 4 : 3;
                    $expectedNotes = $hasApprovedLeave
                        ? ($hasApprovedPaidLeave ? 'Auto-marked: Approved Paid Leave' : 'Auto-marked: Approved Leave')
                        : 'Auto-marked absent: no time-in by shift start.';

                    if ($existingRecord) {
                        $shouldOverride = false;

                        if (is_null($existingRecord->check_in) && is_null($existingRecord->check_out)) {
                            $shouldOverride = true;
                        } elseif ($hasApprovedPaidLeave) {
                            $shouldOverride = true;
                        }

                        if ($shouldOverride && (
                            (int) $existingRecord->shift_id !== (int) $dayShift->id ||
                            (int) $existingRecord->status !== $expectedStatus
                        )) {
                            $existingRecord->update([
                                'shift_id' => $dayShift->id,
                                'status' => $expectedStatus,
                            ]);
                        }
                    } else {
                        Attendance::create([
                            'emp_id' => $employee->id,
                            'shift_id' => $dayShift->id,
                            'attendance_date' => $dateString,
                            'punch_type' => 'in',
                            'time' => null,
                            'status' => $expectedStatus,
                        ]);
                    }

                    continue;
                }

                if ($hasApprovedLeave) {
                    if ($existingRecord) {
                        $shouldOverride = false;

                        if (is_null($existingRecord->check_in) && is_null($existingRecord->check_out)) {
                            $shouldOverride = true;
                        } elseif ($hasApprovedPaidLeave) {
                            $shouldOverride = true;
                        }

                        if ($shouldOverride && (int) $existingRecord->status !== 4) {
                            $existingRecord->update([
                                'status' => 4,
                            ]);
                        }
                    } else {
                        Attendance::create([
                            'emp_id' => $employee->id,
                            'shift_id' => $dayShift->id,
                            'attendance_date' => $dateString,
                            'punch_type' => 'in',
                            'time' => null,
                            'status' => 4,
                        ]);
                    }

                    continue;
                }

                if ($this->isAutoGeneratedAttendanceRecord($existingRecord)) {
                        $existingRecord->delete();
                }
            }
        }
    }

    private function buildLeaveLookups(array $employeeIds, Carbon $rangeStart, Carbon $rangeEnd): array
    {
        $lookups = [
            'approved' => [],
            'paid' => [],
        ];

        if (empty($employeeIds)) {
            return $lookups;
        }

        $approvedLeaves = DB::table('leave_requests')
            ->leftJoin('leave_types', 'leave_requests.leave_type_id', '=', 'leave_types.id')
            ->whereIn('leave_requests.employee_id', $employeeIds)
            ->where('leave_requests.status', 2)
            ->where('leave_requests.start_date', '<=', $rangeEnd->toDateString())
            ->where('leave_requests.end_date', '>=', $rangeStart->toDateString())
            ->select('leave_requests.employee_id', 'leave_requests.start_date', 'leave_requests.end_date', 'leave_types.is_paid')
            ->get();

        foreach ($approvedLeaves as $leave) {
            $leaveStart = Carbon::parse(max($leave->start_date, $rangeStart->toDateString()));
            $leaveEnd = Carbon::parse(min($leave->end_date, $rangeEnd->toDateString()));

            if ($leaveEnd->lt($leaveStart)) {
                continue;
            }

            $cursor = $leaveStart->copy();

            while ($cursor->lte($leaveEnd)) {
                $dateString = $cursor->toDateString();
                $lookups['approved'][$leave->employee_id][$dateString] = true;

                if ((int) $leave->is_paid === 1) {
                    $lookups['paid'][$leave->employee_id][$dateString] = true;
                }

                $cursor->addDay();
            }
        }

        return $lookups;
    }

    private function resolveActiveShiftFromLoadedAssignments(Employee $employee, Carbon $date): ?Shift
    {
        if (!$employee->relationLoaded('shiftAssignments')) {
            return $employee->getActiveShiftForDate($date);
        }

        $dayOfWeek = $date->format('D');
        $dateString = $date->toDateString();

        $assignments = $employee->shiftAssignments
            ->filter(function ($assignment) use ($dateString) {
                $effectiveFrom = $assignment->effective_from instanceof Carbon
                    ? $assignment->effective_from->toDateString()
                    : Carbon::parse($assignment->effective_from)->toDateString();

                $effectiveTo = $assignment->effective_to
                    ? (($assignment->effective_to instanceof Carbon)
                        ? $assignment->effective_to->toDateString()
                        : Carbon::parse($assignment->effective_to)->toDateString())
                    : null;

                return $effectiveFrom <= $dateString && (!$effectiveTo || $effectiveTo >= $dateString);
            })
            ->sortByDesc(function ($assignment) {
                return $assignment->effective_from instanceof Carbon
                    ? $assignment->effective_from->timestamp
                    : Carbon::parse($assignment->effective_from)->timestamp;
            })
            ->values();

        if (Schema::hasColumn('shift_assignments', 'status')) {
            $assignments = $assignments->filter(function ($assignment) {
                return $assignment->status === null || (int) $assignment->status !== 13;
            })->values();
        }

        foreach ($assignments as $assignment) {
            if ($assignment->shift && is_array($assignment->shift->days_of_week) && in_array($dayOfWeek, $assignment->shift->days_of_week, true)) {
                return $assignment->shift;
            }
        }

        return $assignments->first()?->shift;
    }

    private function isAutoGeneratedAttendanceRecord($attendance): bool
    {
        if (!$attendance) {
            return false;
        }

        return is_null($attendance->check_in)
            && is_null($attendance->check_out)
            && in_array((int) $attendance->status, [3, 4], true);
    }

    private function configureLegacyMysqlSchema(): void
    {
        $connection = DB::connection();

        if ($connection->getDriverName() !== 'mysql') {
            return;
        }

        try {
            $version = $connection->getServerVersion();
        } catch (\Throwable $e) {
            return;
        }

        if (version_compare($version, '5.7', '<')) {
            // MySQL 5.6 lacks generation_expression in information_schema.columns.
            $connection->setSchemaGrammar(new LegacyMySqlGrammar($connection));
        }
    }
}
